port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 208.67.222.222
proxies:
  - name: serverssh-vmessid
    server: idray.serverip.my.id
    port: 80
    type: vmess
    uuid: 2829a37a-fffb-4417-8ada-8d4d3b0b8f6b
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: myim3-he.ioh.co.id
    network: ws
    ws-opts:
      path: /api/v1/token/hetoken
      headers:
        Host: myim3-he.ioh.co.id
    udp: true
  - name: serverssh-vmesssg
    server: sg1ray.serverip.my.id
    port: 80
    type: vmess
    uuid: 13598a7d-4a34-4d32-8c80-4aaaba06b292
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: myim3-he.ioh.co.id
    network: ws
    ws-opts:
      path: /api/v1/token/hetoken
      headers:
        Host: myim3-he.ioh.co.id
    udp: true
  - name: serverssh-vlessid
    server: idray.serverip.my.id
    port: 80
    type: vless
    uuid: 524727b4-b0bf-4134-9cc5-2660a2edd3a5
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: myim3-he.ioh.co.id
    network: ws
    ws-opts:
      path: /api/v1/token/hetoken/serverssh/vray
      headers:
        Host: myim3-he.ioh.co.id
    udp: true
  - name: serverssh-vlesssg
    server: sg1ray.serverip.my.id
    port: 80
    type: vless
    uuid: cadf4252-cda8-44c8-be94-515f0314ed53
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: myim3-he.ioh.co.id
    network: ws
    ws-opts:
      path: /api/v1/token/hetoken/serverssh/vray
      headers:
        Host: myim3-he.ioh.co.id
    udp: true
  - name: vlesswhid-globalssh
    server: vless-wh-id01.globalssh.xyz
    port: 80
    type: vless
    uuid: 5b0a4410-9914-42be-a910-14dc0c3d0962
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-wh-id01.globalssh.xyz
    network: ws
    ws-opts:
      path: /api/v1/token/hetoken
      headers:
        Host: myim3-he.ioh.co.id
    udp: true
  - name: vlessikdid-globalssh
    server: vless-ikd-id01.globalssh.xyz
    port: 80
    type: vless
    uuid: f31fc8e1-ae8a-44ad-a071-a54d41dff10a
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-ikd-id01.globalssh.xyz
    network: ws
    ws-opts:
      path: /api/v1/token/hetoken
      headers:
        Host: myim3-he.ioh.co.id
    udp: true
  - name: vmesssg-globalssh
    server: vmess-sg01.globalssh.xyz
    port: 80
    type: vmess
    uuid: 309aa1de-0715-40de-a620-2499c40aa6c1
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vmess-sg01.globalssh.xyz
    network: ws
    ws-opts:
      path: /api/v1/token/hetoken
      headers:
        Host: myim3-he.ioh.co.id
    udp: true
  - name: vlesssgg-globalssh
    server: vless-sg01.globalssh.xyz
    port: 80
    type: vless
    uuid: a0fda4c1-3a6d-418b-8a2a-24ca53e4e2b2
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vless-sg01.globalssh.xyz
    network: ws
    ws-opts:
      path: /api/v1/token/hetoken
      headers:
        Host: myim3-he.ioh.co.id
    udp: true
  - name: vmessikdid-globalssh
    server: vmess-ikd-id01.globalssh.xyz
    port: 80
    type: vmess
    uuid: 59cc619a-1bb3-422d-87ae-46760dfca976
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vmess-ikd-id01.globalssh.xyz
    network: ws
    ws-opts:
      path: /api/v1/token/hetoken/vmess-ws/
      headers:
        Host: myim3-he.ioh.co.id
    udp: true
proxy-groups:
  - name: Trafic-Umum
    type: select
    proxies:
      - serverssh-vmessid
      - serverssh-vmesssg
      - serverssh-vlessid
      - serverssh-vlesssg
      - vlesswhid-globalssh
      - vlessikdid-globalssh
      - vmesssg-globalssh
      - vlesssgg-globalssh
      - vmessikdid-globalssh
      - FALLBACK
      - BEST-PING
      - LOAD-BALANCE
      - DIRECT
  - name: FALLBACK
    type: fallback
    url: https://speed.cloudflare.com/
    interval: 100
    tolerance: 50
    proxies:
      - serverssh-vmessid
      - serverssh-vmesssg
      - serverssh-vlessid
      - serverssh-vlesssg
      - vlesswhid-globalssh
      - vlessikdid-globalssh
      - vmesssg-globalssh
      - vlesssgg-globalssh
      - vmessikdid-globalssh
  - name: BEST-PING
    type: url-test
    url: https://speed.cloudflare.com/
    interval: 300
    tolerance: 50
    proxies:
      - serverssh-vmessid
      - serverssh-vmesssg
      - serverssh-vlessid
      - serverssh-vlesssg
      - vlesswhid-globalssh
      - vlessikdid-globalssh
      - vmesssg-globalssh
      - vlesssgg-globalssh
      - vmessikdid-globalssh
  - name: LOAD-BALANCE
    type: load-balance
    strategy: round-robin
    url: https://speed.cloudflare.com/
    interval: 300
    proxies:
      - vmesssg-globalssh
      - vlesssgg-globalssh
rule-providers:
  rule_Direct:
    type: file
    behavior: classical
    path: "./rule_direct.yaml"
  clash:
    type: http
    behavior: domain
    url: https://howdy.id/download/rules/clash.txt
    path: ./providers/rule-provider_clash.yaml
    interval: 86400
rules:
 - PROCESS-NAME,xray.exe,DIRECT
 # - RULE-SET,rule_Direct,DIRECT,no-resolve
 - RULE-SET,clash,REJECT
 - MATCH,Trafic-Umum
