port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  nameserver:
    - 8.8.8.8
    - 1.0.0.1
    - https://dns.google/dns-query
  fallback:
    - 1.1.1.1
    - 8.8.4.4
    - https://cloudflare-dns.com/dns-query
    - 112.215.203.254
  default-nameserver:
    - 8.8.8.8
    - 1.1.1.1
    - 112.215.203.254
proxies:
  - name: vmess-sg01.globalssh.xyz
    server: nontontv.vidio.com
    port: 80
    type: vmess
    uuid: 0e983c57-1b09-4e42-a815-cb05d292000b
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: vmess-sg01.globalssh.xyz
    network: ws
    ws-opts:
      path: /vmess-ws
      headers:
        Host: vmess-sg01.globalssh.xyz
    udp: true
  - name: id1-ray.ipservers.xyz
    server: nontontv.vidio.com
    port: 80
    type: vmess
    uuid: 1b58d604-0b4c-45b5-aaff-bce8f3905a36
    alterId: 0
    cipher: auto
    tls: false
    skip-cert-verify: true
    servername: id1-ray.ipservers.xyz
    network: ws
    ws-opts:
      path: /JAGOANSSH/
      headers:
        Host: id1-ray.ipservers.xyz
    udp: true
proxy-groups:
  - name: FASTSSH-SSHKIT-HOWDY
    type: select
    proxies:
      - vmess-sg01.globalssh.xyz
      - id1-ray.ipservers.xyz
      - BEST-PING
      - DIRECT
  - name: BEST-PING
    type: url-test
    url: http://hi.bonds.id/ping
    interval: 300
    tolerance: 50
    proxies:
      - vmess-sg01.globalssh.xyz
      - id1-ray.ipservers.xyz
rules:
  - MATCH,FASTSSH-SSHKIT-HOWDY
